# Changes made to manifest files such as this are the 'live' versions referred to in ArgoCD's U.I
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.appName}}"
  labels:
    app: "{{.Values.appName}}"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
      - name: "{{.Values.appName}}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: dockerhub-auth