# Changes made to manifest files such as this are the 'live' versions referred to in ArgoCD's U.I
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalproject
  labels:
    app: personalproject
spec:
  replicas: {{ .values.replicaCount }}
  selector:
    matchLabels:
      app: personalproject
  template:
    metadata:
      labels:
        app: personalproject
    spec:
      containers:
      - name: personalproject
        image: "{{ .values.image.repository }}:{{ .values.image.tag }}"
        imagePullPolicy: "{{ .values.image.pullPolicy }}"
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: dockerhub-auth