# apiVersion: v1
# kind: Service
# metadata:
#   name: "{{ .Values.appName }}-service"
# spec:
#   type: "{{ .Values.service.type }}"
#   selector:
#     app: "{{ .Values.appName }}"
#   ports:
#     - name: metrics
#     - port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.port }}
#       nodePort: {{ .Values.service.nodePort }}

apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: personalproject:/Service:argocd/personalproject-service
  name: personalproject-service
  namespace: argocd
spec:
  ports:
    - name: metrics
    - nodePort: 30008
      port: 8081
      targetPort: 8081
  selector:
    app: personalproject
  type: NodePort