apiVersion: v1
kind: Service
metadata:
  name: personalproject-service
spec:
  type: NodePort
  selector:
    app: personalproject
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}