apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: "{{ .Values.appName }}"
  ports:
    - name: metrics
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}