apiVersion: v1
kind: Service
metadata:
  name: personalproject-service
spec:
  type: "{{ .values.service.type }}"
  selector:
    app: personalproject
  type: "{{ .Values.service.type }}"
  ports:
    - port: {{ .values.service.port }}
      targetPort: {{ .values.service.port }}
      nodePort: {{ .values.service.nodePort }}