replicaCount: 3
revisionHistoryLimit: 3
appName: capstoneproject1

image:
  repository: enitanm/personalproject
  tag: v1.0.34
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8082
  nodePort: 30009

resources: {}
