replicaCount: 3
revisionHistoryLimit: 3
appName: capstoneproject1

image:
  repository: enitanm/personalproject
  tag: v2.0.41
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8088
  nodePort: 30009

resources: {}
