replicaCount: 1
revisionHistoryLimit: 3
appName: capstoneproject1

image:
  repository: enitanm/personalproject
  tag: v2.0.2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8082
  nodePort: 30009

resources: {}
