replicaCount: 1
revisionHistoryLimit: 3
appName: capstoneproject1

image:
  repository: enitanm/personalproject
  tag: v2.0.57
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8081
  nodePort: 30008

resources: {}
