apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalproject
  labels:
    app: personalproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personalproject
  template:
    metadata:
      labels:
        app: personalproject
    spec:
      containers:
      - name: personalproject
        image: capstoneteam1-avd2dagya7gjdhda.azurecr.io/personalproject:v1.0.90
      imagePullSecrets:
      - name: acr-auth
        ports:
        - containerPort: 8081