apiVersion: v1
kind: Service
metadata:
  name: personalproject-service
spec:
  type: NodePort
  selector:
    app: personalproject
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008